name: vip_bus_ticketing_system
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  geolocator: ^8.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.10
  permission_handler: ^10.2.0
  http: 1.1.0
  firebase_core: ^1.20.0
  firebase_auth: ^4.1.1


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^2.7.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash_screen_lottie.json
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/vip_logo_transparent.png
    - assets/images/8.jpg
    - assets/images/google.png
    - assets/images/pp.png
    - assets/images/44.jpg
  

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
        
          
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
      
 
